### PR TITLE
AQ-26856 Update Newtonsoft.Json to 12.0.3

### PR DESCRIPTION
**Pull request by MartinBenn-AI**
Remove Newtonsoft.json.dll from repository.
Make Newtonsoft.Json a NuGet package.
Upgrade Newtonsoft.Json to 12.0.3.

### CODE REVIEW

**Comment by kimsharpe-ai** [comment]
@MartinBenn-AI 
can you wait to merge this until next week? 
I have 3 reports lined up to check-in this week and I would need to do double merges if this one goes through first.

**Comment by MartinBenn-AI** [comment]
@kimsharpe-ai we can hold off, but as it is right now we need this to get merged to unblock running reports in our 21.1 environment.

Are these reports planned for 21.1 and 20.4?

**Comment by kimsharpe-ai** [comment]
@MartinBenn-AI not 100% sure about 20.4 vs 21.1 but if I can get these in now and do a release before your change then that will cover both cases. 
Also benefit is that you will be able to add your changes to the new reports - which they need.

**Comment by MartinBenn-AI** [comment]
We already have a branch for 20.4 which any changes that are targeted for that release will need to go into that as well. I think what you are saying that is if I hold off on merging this, you can apply the same fix to 21.1 (this branch) and 20.4 (release/20.4) without making any project changes right? That makes sense to me and I think we can put up with the broken tests for a few days.

**Comment by kimsharpe-ai** [comment]
@MartinBenn-AI ok thanks!

**Comment by kimsharpe-ai** [comment]
@MartinBenn-AI 
Thanks for holding off on merge - today I added 4 new custom reports which need to be updated. 
That's the last of new reports to go into 21.1.
I wonder if the dlls in the folder ExternalLibraries/Aqts ought to be updated too? 
They are old - Aqts version 20.3.65

**Comment by MartinBenn-AI** [comment]
I will update the AQTS libraries since we are on ServiceStack 5.10.4 now as well as re-work this PR to cover those new reports. Thanks for the reminder!

**Pull request merged**
